### ISSUE TITLE
error downloading streamflow

### ISSUE THREAD

**Issue by xhqiao89** [CUAHSI/HydroDesktop#218]
<b>msomos[CodePlex]</b> <br />Hi I am trying to download river flow but I am getting this error. Could you please help me to figure what the problem is?

Thanks 

Marcelo 

3:52:36 PM Starting downloading... 
3:52:36 PM Connecting to server... 
3:52:38 PM Downloading... 
3:52:38 PM Downloading... 
3:52:39 PM Downloading... 
3:52:39 PM Downloading... 
3:52:39 PM Downloaded GREEN RIVER NEAR COLRAIN, MA|Discharge, cubic feet per second (1 of 1).

3:52:39 PM Error in GREEN RIVER NEAR COLRAIN, MA|Discharge, cubic feet per second:

Object reference not set to an instance of an object. 
Exception details: 
Message: Object reference not set to an instance of an object. 
Stacktrace: at HydroDesktop.DataDownload.Downloading.Downloader.DataSeriesFromXml(OneSeriesDownloadInfo dInfo) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\Downloader.cs:line 127

at HydroDesktop.DataDownload.Downloading.DownloadManager.DoSave(Object state) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\DownloadManager.cs:line 429

Inner exception: Object reference not set to an instance of an object.
3:52:39 PM 
Total: 
ServiceURL SiteCode VariableCode StartDate EndDate DownloadTime Status ErrorMessage
http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx?WSDL NWISDV:01170100 NWISDV:00060/DataType=MEAN 12/24/1984 12:00:00 AM 12/31/2014 12:00:00 AM 00:00:02 Error Object
 reference not set to an instance of an object.
3:52:39 PM Downloading... 
3:52:39 PM Download Complete. 
3:54:11 PM Re-download series (1 of 1) started... 
3:54:11 PM Connecting to server... 
3:54:11 PM Downloading... 
3:54:12 PM Downloading... 
3:54:13 PM Downloading... 
3:54:13 PM Downloading... 
3:54:13 PM Downloaded GREEN RIVER NEAR COLRAIN, MA|Discharge, cubic feet per second (1 of 1).

3:54:13 PM Error in GREEN RIVER NEAR COLRAIN, MA|Discharge, cubic feet per second:

Object reference not set to an instance of an object. 
Exception details: 
Message: Object reference not set to an instance of an object. 
Stacktrace: at HydroDesktop.DataDownload.Downloading.Downloader.DataSeriesFromXml(OneSeriesDownloadInfo dInfo) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\Downloader.cs:line 127

at HydroDesktop.DataDownload.Downloading.DownloadManager.DoSave(Object state) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\DownloadManager.cs:line 429

Inner exception: Object reference not set to an instance of an object.
3:54:13 PM 
Total: 
ServiceURL SiteCode VariableCode StartDate EndDate DownloadTime Status ErrorMessage
http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx?WSDL NWISDV:01170100 NWISDV:00060/DataType=MEAN 12/24/1984 12:00:00 AM 12/31/2014 12:00:00 AM 00:00:02 Error Object
 reference not set to an instance of an object.
3:54:13 PM Downloading... 
3:54:13 PM Download Complete. 
3:58:14 PM Re-download series (1 of 1) started... 
3:58:14 PM Connecting to server... 
3:58:15 PM Downloading... 
3:58:16 PM Downloading... 
3:58:17 PM Downloading... 
3:58:17 PM Downloading... 
3:58:17 PM Downloaded DEERFIELD RIVER AT CHARLEMONT, MA|Discharge, cubic feet per second (1 of 1).

3:58:17 PM Error in DEERFIELD RIVER AT CHARLEMONT, MA|Discharge, cubic feet per second:

Object reference not set to an instance of an object. 
Exception details: 
Message: Object reference not set to an instance of an object. 
Stacktrace: at HydroDesktop.DataDownload.Downloading.Downloader.DataSeriesFromXml(OneSeriesDownloadInfo dInfo) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\Downloader.cs:line 127

at HydroDesktop.DataDownload.Downloading.DownloadManager.DoSave(Object state) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\DownloadManager.cs:line 429

Inner exception: Object reference not set to an instance of an object.
3:58:17 PM 
Total: 
ServiceURL SiteCode VariableCode StartDate EndDate DownloadTime Status ErrorMessage
http://hydroportal.cuahsi.org/nwisdv/cuahsi_1_1.asmx?WSDL NWISDV:01168500 NWISDV:00060/DataType=MEAN 12/24/1984 12:00:00 AM 12/31/2014 12:00:00 AM 00:00:02 Error Object
 reference not set to an instance of an object.
3:58:17 PM Downloading... 
3:58:17 PM Download Complete.

**Comment by xhqiao89** [comment]
<b>b24728[CodePlex]</b> <br />I am having this issue too ... I tried downloading 28 time series datasets from San Antonio and Guadalupe watersheds (Texas) and got the same Object reference not set to an instance of an object. error for all 28 datasets. Here is a sample
 from the log: 
9:14:01 PM Starting downloading...
9:14:01 PM Connecting to server...
9:14:04 PM Downloading...
9:14:04 PM Downloading...
9:14:04 PM Downloaded San Antonio Rv nr Floresville, TX|Gage height, feet (1 of 1).
9:14:04 PM Error in San Antonio Rv nr Floresville, TX|Gage height, feet:
Object reference not set to an instance of an object.
Exception details:
Message: Object reference not set to an instance of an object.
Stacktrace: at HydroDesktop.DataDownload.Downloading.Downloader.DataSeriesFromXml(OneSeriesDownloadInfo dInfo) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\Downloader.cs:line 127
at HydroDesktop.DataDownload.Downloading.DownloadManager.DoSave(Object state) in g:\TeamCity\buildAgent\work\2283af7616268485\Source\DataDownload\DataDownload\Downloading\DownloadManager.cs:line 429
Inner exception: Object reference not set to an instance of an object.
9:14:04 PM 
Total:
ServiceURL SiteCode VariableCode StartDate EndDate DownloadTime Status ErrorMessage
http://hydroportal.cuahsi.org/nwisuv/cuahsi_1_1.asmx?WSDL NWISUV:08183200 NWISUV:00065 10/1/2015 12:00:00 AM 1/14/2016 12:00:00 AM 00:00:02 Error Object reference not
 set to an instance of an object.
9:14:04 PM Downloading...
9:14:04 PM Download Complete.

I saw a post from 2010 with this issue and it was a problem with an update on the server end and there was a URL change work-around ... is that still the case?
Thanks
:)
Chris
