### ISSUE TITLE
Errors on download EPA data

### ISSUE THREAD

**Issue by xhqiao89** [CUAHSI/HydroDesktop#29]
<b>rhooper[CodePlex]</b> <br />On some series,the catalog returns that data is available at a site and then on download, the download fails because no data is available at that site, so catalog is not synched properly with database. I can provide specific examples and log if that helps,
 but seems to occur at about 50% of sites I've tried so far.

**Comment by xhqiao89** [comment]
<b>danames[CodePlex]</b> <br />This may become resolved as the water data center takes over from SDSC for the data catalog.


Need some more tests to determine if it's HD or Catalog...

**Comment by xhqiao89** [comment]
<b>ericch[CodePlex]</b> <br />Nevermind, after doing even more testing I am now getting more results that are producing errors due to not having that series in the xml file. I'll reopen it.

**Comment by xhqiao89** [comment]
<b>ericch[CodePlex]</b> <br />I'll put this as resolved for now.

**Comment by xhqiao89** [comment]
<b>ericch[CodePlex]</b> <br />I have been doing some testing on this one and it seems now that EPA sites successfully download with a success rate far greater than 50%

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />Another error reported by CRRicks: 

12:32:03 PM Starting downloading... 
12:32:03 PM Connecting to server... 
12:32:34 PM Exception has been thrown by the target of an invocation. 
12:32:34 PM Exception has been thrown by the target of an invocation. 
Exception details: 
Message: Exception has been thrown by the target of an invocation. 
Stacktrace: at HydroDesktop.Search.Download.Downloader.DownloadXmlDataValues(DownloadInfo info) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\Downloader.cs:line 90

at HydroDesktop.Search.Download.DownloadManager.DoDownload(Object state) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\DownloadManager.cs:line 255

Inner exception: Exception has been thrown by the target of an invocation. 
Exception details: 
Message: Exception has been thrown by the target of an invocation. 
Stacktrace: at HydroDesktop.Search.Download.Downloader.DownloadXmlDataValues(DownloadInfo info) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\Downloader.cs:line 90

at HydroDesktop.Search.Download.DownloadManager.DoDownload(Object state) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\DownloadManager.cs:line 255

Inner exception: Exception has been thrown by the target of an invocation. 
12:32:34 PM Processed series 1 of 3 
12:32:34 PM Processed series 2 of 3 
12:32:34 PM Exception has been thrown by the target of an invocation. 
Exception details: 
Message: Exception has been thrown by the target of an invocation. 
Stacktrace: at HydroDesktop.Search.Download.Downloader.DownloadXmlDataValues(DownloadInfo info) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\Downloader.cs:line 90

at HydroDesktop.Search.Download.DownloadManager.DoDownload(Object state) in g:\TeamCity\buildAgent\work\f7ff7e4eb69f4f40\Source\Plugins\Search2\Search2Plugin\Download\DownloadManager.cs:line 255

Inner exception: Exception has been thrown by the target of an invocation. 
12:32:34 PM Processed series 3 of 3 
12:32:34 PM Processed series 3 of 3 
12:32:34 PM Download Complete.
12:32:34 PM
Total: 
ServiceURL SiteCode VariableCode StartDate EndDate DownloadTime Status ErrorMessage

http://river.sdsc.edu/wateroneflow/EPA/cuahsi_1_0.asmx?WSDL EPA:UTAHDWQ:5913520 EPA:1473-1 1/1/2000 12:00:00 AM 9/30/2010 12:00:00 AM 00:00:31.7180000 Error Exception has
 been thrown by the target of an invocation. 
http://river.sdsc.edu/wateroneflow/EPA/cuahsi_1_0.asmx?WSDL EPA:UTAHDWQ:5913540 EPA:1473-1 1/1/2000 12:00:00 AM 9/30/2010 12:00:00 AM 00:00:31.6980000 Error Exception has
 been thrown by the target of an invocation.
http://river.sdsc.edu/wateroneflow/EPA/cuahsi_1_0.asmx?WSDL EPA:UTAHDWQ:5913550 EPA:1473-1 1/1/2000 12:00:00 AM 9/30/2010 12:00:00 AM 00:00:31.8080000 Error Exception
 has been thrown by the target of an invocation.

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />We need to log this as a HydroCatalog issue and provide an example list of series where the download fails
