### ISSUE TITLE
Unhandled Exceptions when Opening Interpolation Tools

### ISSUE THREAD

**Issue by xhqiao89** [CUAHSI/HydroDesktop#71]
<b>jpollak[CodePlex]</b> <br />I encounter Unhandled Exception error messages when clicking either the Geostatisical Methods or Deterministic Methods buttons:

quotUnable to cast object of type 'DotSpatial.Data.InRamImageData' to type 'DotSpatial.Data.IFeatureSet'.quot

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />One more detail:
The exception occurs if the 'Online basemap' layer is inside a group.
It doesn't occur if the 'Online Basemap' is not part of any group.

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />Additional details:
The exception occurs if 'Online Basemap' layer is in the legend.
It doesn't occur if 'Online Basemap' is set to None.
After this exception the dialog can't be closed.

**Comment by xhqiao89** [comment]
<b>mogikanin[CodePlex]</b> <br />Steps to reproduce:

Search for All, area - Reno, Kansas Try to open Geostatisical Methods or Deterministic Methods Stack trace:
Unable to cast object of type 'DotSpatial.Data.InRamImageData' to type 'DotSpatial.Data.IFeatureSet'.
Inner: NULL
Stack trace: at GeostatisticalTool.Classes.ConfigurationMethod.UpdataLayer()
at GeostatisticalTool.Classes.ConfigurationMethod..ctor(Map map, ListBox method, ListBox output, ComboBox layer, ComboBox field, ComboBox transformation, ComboBox trend, Boolean filter)
at GeostatisticalTool.Forms.Interpolators.Interpolators_Load(Object sender, EventArgs e)
at System.Windows.Forms.Form.OnLoad(EventArgs e)
at System.Windows.Forms.Form.OnCreateControl()
at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
at System.Windows.Forms.Control.CreateControl()
at System.Windows.Forms.Control.WmShowWindow(Message m)
at System.Windows.Forms.Control.WndProc(Message m)
at System.Windows.Forms.ScrollableControl.WndProc(Message m)
at System.Windows.Forms.ContainerControl.WndProc(Message m)
at System.Windows.Forms.Form.WmShowWindow(Message m)
at System.Windows.Forms.Form.WndProc(Message m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />possibly related to: 
http://hydrodesktop.codeplex.com/workitem/8515
