### ISSUE TITLE
ArgumentOutOfRangeException on Data Download

### ISSUE THREAD

**Issue by xhqiao89** [CUAHSI/HydroDesktop#96]
<b>twhitvine[CodePlex]</b> <br />I was following the Elbe Precipitation tutorial from the Documentation page. I was downloading precip data for all sites when I got this error.

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

Parameter name: index 
at System.Collections.Generic.List`1.get_Item(Int32 index) 
at HydroDesktop.DataDownload.Downloading.DownloadManager.DoDownload(Object state) in g:\TeamCity\buildAgent\work\e54ee16d10a0068\Source\DataDownload\DataDownload\Downloading\DownloadManager.cs:line 374

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)

at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by xhqiao89** [comment]
<b>twhitvine[CodePlex]</b> <br />I cannot reproduce this error.
